"""Narrated Webinar — the pitch for the narrated-webinar skill itself.

A short, X-ready demo: instead of having Claude draft an email nobody reads,
make a narrated webinar — visual, narrated, easy to understand. This file is
also the thing it describes: one config file = the whole presentation.

Built with the narrated-webinar Claude Code skill.
"""

META = {
    "title": "Narrated Webinar",
    "eyebrow": "CLAUDE CODE SKILL",
    "subtitle": "This whole thing — the voice, the slides moving with it, the player you're using — came out of one text file.",
    "preview": [
        {"num": "PART ONE", "title": "The email nobody reads"},
        {"num": "PART TWO", "title": "One file → voice + visuals"},
        {"num": "PART THREE", "title": "Post it anywhere"},
    ],
    "start_meta": "~2 minutes · narrated · 3 segments",
    "property_line": "narrated-webinar · a Claude Code skill",
    "sidebar_eyebrow": "Claude Code Skill",
    "sidebar_title": "Narrated Webinar",
    "stage_property": "narrated-webinar · a Claude Code skill",
}

VOICE = {
    "id": "EXAVITQu4vr4xnSDxMaL",
    "model": "eleven_multilingual_v2",
    "settings": {
        "stability": 0.55,
        "similarity_boost": 0.8,
        "style": 0.22,
        "use_speaker_boost": True,
    },
}

SCENES = {
    # ----------------------------------------------------------------- email
    "email": {
        "html": """
        <div class="email-window">
          <div class="email-bar">
            <span class="email-dot"></span><span class="email-dot"></span><span class="email-dot"></span>
            <span class="email-from">Draft · generated by Claude</span>
          </div>
          <div class="email-head">
            <div class="email-row"><span class="email-k">To</span><span class="email-v">the whole team</span></div>
            <div class="email-row"><span class="email-k">Subject</span><span class="email-v">Re: the new thing — please read (it's long)</span></div>
          </div>
          <div class="email-body">
            <span class="email-line"></span>
            <span class="email-line"></span>
            <span class="email-line"></span>
            <span class="email-line short"></span>
            <span class="email-line"></span>
            <span class="email-line"></span>
            <span class="email-line short"></span>
            <span class="email-line"></span>
            <span class="email-line"></span>
            <span class="email-line short"></span>
          </div>
        </div>
        <div class="email-stamp">SKIMMED</div>
        <div class="email-better">There has to be a better way.</div>
""",
        "css": """
  .scene-email {
    display: flex; align-items: center; justify-content: center;
    padding: 3rem;
    position: relative;
  }
  .email-window {
    width: 540px; max-width: 90%;
    background: #f5f3ee;
    border-radius: 10px;
    box-shadow: 0 30px 80px rgba(0,0,0,0.5);
    overflow: hidden;
    color: #1a2a4f;
    opacity: 0;
    transform: translateY(24px) scale(0.97);
    transition: opacity 0.8s ease, transform 0.9s ease, filter 1.2s ease;
  }
  .scene-email.active .email-window { opacity: 1; transform: translateY(0) scale(1); }
  /* When the narration says it gets half-skimmed, the whole thing greys out. */
  .scene-email.skimmed .email-window { filter: grayscale(1) brightness(0.82); opacity: 0.55; }

  .email-bar {
    display: flex; align-items: center; gap: 0.4rem;
    padding: 0.6rem 0.9rem;
    background: #e3ded2;
    border-bottom: 1px solid rgba(0,0,0,0.08);
  }
  .email-dot { width: 11px; height: 11px; border-radius: 50%; background: #c4bdab; }
  .email-dot:nth-child(1) { background: #e0726a; }
  .email-dot:nth-child(2) { background: #e0b94f; }
  .email-dot:nth-child(3) { background: #79b06a; }
  .email-from {
    margin-left: auto;
    font-size: 0.7rem; font-weight: 700; letter-spacing: 0.08em;
    color: #6a6657; text-transform: uppercase;
  }
  .email-head { padding: 1rem 1.4rem 0.6rem; border-bottom: 1px solid rgba(0,0,0,0.07); }
  .email-row { display: flex; gap: 0.8rem; padding: 0.2rem 0; font-size: 0.85rem; }
  .email-k { width: 56px; color: #8a8675; font-weight: 700; }
  .email-v { color: #2a3550; font-weight: 600; }
  .email-body { padding: 1.2rem 1.4rem 1.6rem; }
  .email-line {
    display: block; height: 9px; border-radius: 3px;
    background: #c9c3b3;
    margin: 0.62rem 0;
    transform-origin: left center;
    transform: scaleX(0);
    transition: transform 0.5s ease;
  }
  .email-line.short { width: 62%; }
  .scene-email.active .email-line { transform: scaleX(1); }
  .scene-email.active .email-line:nth-child(1)  { transition-delay: 1.0s; }
  .scene-email.active .email-line:nth-child(2)  { transition-delay: 1.3s; }
  .scene-email.active .email-line:nth-child(3)  { transition-delay: 1.6s; }
  .scene-email.active .email-line:nth-child(4)  { transition-delay: 1.9s; }
  .scene-email.active .email-line:nth-child(5)  { transition-delay: 2.2s; }
  .scene-email.active .email-line:nth-child(6)  { transition-delay: 2.5s; }
  .scene-email.active .email-line:nth-child(7)  { transition-delay: 2.8s; }
  .scene-email.active .email-line:nth-child(8)  { transition-delay: 3.1s; }
  .scene-email.active .email-line:nth-child(9)  { transition-delay: 3.4s; }
  .scene-email.active .email-line:nth-child(10) { transition-delay: 3.7s; }

  .email-stamp {
    position: absolute;
    top: 38%; left: 50%;
    transform: translate(-50%, -50%) rotate(-14deg) scale(1.6);
    font-size: 2.4rem; font-weight: 900; letter-spacing: 0.2em;
    color: var(--red);
    border: 5px solid var(--red);
    border-radius: 10px;
    padding: 0.4rem 1.4rem;
    opacity: 0;
    text-transform: uppercase;
    transition: opacity 0.5s ease, transform 0.5s ease;
  }
  .scene-email.skimmed .email-stamp {
    opacity: 0.9;
    transform: translate(-50%, -50%) rotate(-14deg) scale(1);
  }

  .email-better {
    position: absolute;
    bottom: 12%; left: 0; right: 0;
    text-align: center;
    font-size: clamp(1.1rem, 2.2vw, 1.6rem);
    font-style: italic;
    color: var(--gold-bright);
    opacity: 0;
    transform: translateY(14px);
    transition: opacity 1s ease, transform 1s ease;
  }
  .scene-email.better .email-better { opacity: 1; transform: translateY(0); }
""",
    },
    # --------------------------------------------------------------- webinar
    "webinar": {
        "html": """
        <div class="web-flow">
          <div class="web-file">
            <div class="web-file-name">webinar.py</div>
            <div class="web-code">
              <div class="web-cl"><span class="web-key">META</span> = { <span class="web-dim">title, eyebrow, …</span> }</div>
              <div class="web-cl"><span class="web-key">VOICE</span> = { <span class="web-dim">id, model, settings</span> }</div>
              <div class="web-cl"><span class="web-key">SCENES</span> = { <span class="web-dim">email, webinar, ship</span> }</div>
              <div class="web-cl"><span class="web-key">CHAPTERS</span> = [</div>
              <div class="web-cl web-indent">{ <span class="web-str">"scene"</span>: <span class="web-val">"webinar"</span>,</div>
              <div class="web-cl web-indent2"><span class="web-str">"narration"</span>: <span class="web-nar">"Instead of drafting an email…"</span></div>
              <div class="web-cl web-indent">} ]</div>
            </div>
            <div class="web-file-tag">one source of truth</div>
          </div>

          <div class="web-arrow">→</div>

          <div class="web-outs">
            <div class="web-out web-out-voice">
              <div class="web-bars"><i></i><i></i><i></i><i></i><i></i><i></i><i></i></div>
              <div class="web-out-label">ElevenLabs voiceover</div>
            </div>
            <div class="web-out web-out-scene">
              <div class="web-scene-mini"><span></span><span></span><span></span></div>
              <div class="web-out-label">Animated scene per line</div>
            </div>
            <div class="web-out web-out-player">
              <div class="web-player-mini">
                <div class="web-pm-side"><b></b><b></b><b></b></div>
                <div class="web-pm-stage"><div class="web-pm-prog"></div></div>
              </div>
              <div class="web-out-label">A real player</div>
            </div>
          </div>
        </div>

        <div class="web-tagline">
          <span>Visual.</span><span>Narrated.</span><span>Easy to understand.</span>
        </div>
""",
        "css": """
  .scene-webinar {
    display: flex; flex-direction: column;
    align-items: center; justify-content: center;
    padding: 2.5rem 4rem;
    gap: 2.4rem;
  }
  .web-flow {
    display: flex; align-items: center; justify-content: center;
    gap: 2rem;
    width: 100%; max-width: 1100px;
  }

  .web-file {
    flex: 0 0 auto;
    width: 420px;
    background: #0c172e;
    border: 1px solid rgba(212, 166, 71, 0.35);
    border-radius: 14px;
    padding: 1.1rem 1.3rem 1.4rem;
    box-shadow: 0 24px 60px rgba(0,0,0,0.45);
    opacity: 0; transform: translateX(-30px);
    transition: opacity 0.8s ease, transform 0.8s ease;
  }
  .scene-webinar.active .web-file { opacity: 1; transform: translateX(0); transition-delay: 0.6s; }
  .web-file-name {
    font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
    font-size: 0.78rem; color: var(--gold-bright); letter-spacing: 0.05em;
    margin-bottom: 0.8rem; padding-bottom: 0.6rem;
    border-bottom: 1px solid var(--border);
  }
  .web-code {
    font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
    font-size: 0.74rem; line-height: 1.75; color: var(--text);
  }
  .web-cl { white-space: nowrap; }
  .web-indent { padding-left: 1.2rem; }
  .web-indent2 { padding-left: 2.4rem; }
  .web-key { color: var(--blue); font-weight: 700; }
  .web-dim { color: var(--text-dimmer); }
  .web-str { color: #7fd6a0; }
  .web-val { color: var(--gold); }
  .web-nar {
    color: var(--gold-bright);
    background: rgba(244, 200, 105, 0.12);
    border-radius: 4px; padding: 0 4px;
  }
  .web-file-tag {
    margin-top: 1rem; font-size: 0.68rem; letter-spacing: 0.18em;
    text-transform: uppercase; color: var(--gold);
    text-align: center; font-weight: 700;
  }

  .web-arrow {
    color: var(--gold); font-size: 2rem; font-weight: 700;
    opacity: 0; transform: scale(0.5);
    transition: opacity 0.6s ease, transform 0.6s ease;
  }
  .scene-webinar.active .web-arrow { opacity: 1; transform: scale(1); transition-delay: 9s; }

  .web-outs { display: flex; flex-direction: column; gap: 0.9rem; flex: 0 0 auto; width: 320px; }
  .web-out {
    display: flex; align-items: center; gap: 1rem;
    background: rgba(20, 35, 71, 0.55);
    border: 1px solid var(--border);
    border-radius: 12px;
    padding: 0.9rem 1.1rem;
    opacity: 0; transform: translateX(26px);
    transition: opacity 0.7s ease, transform 0.7s ease;
  }
  .scene-webinar.active .web-out { opacity: 1; transform: translateX(0); }
  .scene-webinar.active .web-out-voice  { transition-delay: 15.5s; border-color: rgba(96,165,250,0.4); }
  .scene-webinar.active .web-out-scene  { transition-delay: 19s; border-color: rgba(244,200,105,0.4); }
  .scene-webinar.active .web-out-player { transition-delay: 23s; border-color: rgba(74,222,128,0.4); }
  .web-out-label { font-size: 0.9rem; font-weight: 600; color: var(--text); }

  /* voice — equalizer bars */
  .web-bars { display: flex; align-items: flex-end; gap: 3px; height: 34px; width: 54px; flex: 0 0 auto; }
  .web-bars i {
    flex: 1; background: var(--blue); border-radius: 2px; height: 30%;
  }
  .scene-webinar.active .web-out-voice .web-bars i { animation: webEq 1s ease-in-out infinite; }
  .web-bars i:nth-child(1) { animation-delay: 0s; }
  .web-bars i:nth-child(2) { animation-delay: 0.12s; }
  .web-bars i:nth-child(3) { animation-delay: 0.24s; }
  .web-bars i:nth-child(4) { animation-delay: 0.36s; }
  .web-bars i:nth-child(5) { animation-delay: 0.48s; }
  .web-bars i:nth-child(6) { animation-delay: 0.6s; }
  .web-bars i:nth-child(7) { animation-delay: 0.72s; }
  @keyframes webEq { 0%,100% { height: 25%; } 50% { height: 100%; } }

  /* scene — three blocks fading in a loop */
  .web-scene-mini { display: flex; gap: 4px; width: 54px; height: 34px; flex: 0 0 auto; }
  .web-scene-mini span { flex: 1; border-radius: 3px; background: var(--gold); opacity: 0.3; }
  .scene-webinar.active .web-out-scene .web-scene-mini span { animation: webPulse 1.8s ease-in-out infinite; }
  .web-scene-mini span:nth-child(2) { animation-delay: 0.4s; }
  .web-scene-mini span:nth-child(3) { animation-delay: 0.8s; }
  @keyframes webPulse { 0%,100% { opacity: 0.25; } 50% { opacity: 1; } }

  /* player — mini chrome */
  .web-player-mini {
    width: 54px; height: 34px; flex: 0 0 auto;
    display: flex; gap: 3px;
    border: 1px solid var(--border); border-radius: 5px; padding: 3px;
    background: var(--navy-900);
  }
  .web-pm-side { width: 14px; display: flex; flex-direction: column; gap: 3px; }
  .web-pm-side b { display: block; height: 4px; border-radius: 1px; background: var(--green); opacity: 0.6; }
  .web-pm-side b:first-child { opacity: 1; }
  .web-pm-stage { flex: 1; background: rgba(255,255,255,0.05); border-radius: 3px; position: relative; }
  .web-pm-prog { position: absolute; left: 0; bottom: 0; height: 3px; width: 30%; background: var(--green); border-radius: 2px; }
  .scene-webinar.active .web-out-player .web-pm-prog { animation: webProg 3.5s linear infinite; }
  @keyframes webProg { from { width: 8%; } to { width: 96%; } }

  .web-tagline { display: flex; gap: 1.6rem; }
  .web-tagline span {
    font-size: clamp(0.95rem, 1.6vw, 1.25rem);
    font-weight: 800; letter-spacing: 0.04em;
    color: var(--gold-bright);
    opacity: 0; transform: translateY(12px);
    transition: opacity 0.6s ease, transform 0.6s ease;
  }
  .scene-webinar.active .web-tagline span:nth-child(1) { transition-delay: 29s; }
  .scene-webinar.active .web-tagline span:nth-child(2) { transition-delay: 29.6s; }
  .scene-webinar.active .web-tagline span:nth-child(3) { transition-delay: 30.2s; }
  .scene-webinar.active .web-tagline span { opacity: 1; transform: translateY(0); }
""",
    },
    # ------------------------------------------------------------------ ship
    "ship": {
        "html": """
        <div class="ship-artifacts">
          <div class="ship-folder">
            <div class="ship-folder-tab"></div>
            <div class="ship-folder-body">
              <div class="ship-file"><span class="ship-fi">■</span> index.html</div>
              <div class="ship-file"><span class="ship-fi">▸</span> audio/</div>
            </div>
          </div>
          <div class="ship-mp4">
            <div class="ship-mp4-play">▶</div>
            <div class="ship-mp4-label">.mp4</div>
          </div>
        </div>

        <div class="ship-hosts">
          <span>Netlify</span><span>Cloudflare Pages</span><span>GitHub Pages</span><span>S3</span><span>X</span>
        </div>

        <div class="ship-cta">/narrated-webinar</div>
        <div class="ship-closer">This was the pitch. It was also the demo.</div>
""",
        "css": """
  .scene-ship {
    display: flex; flex-direction: column;
    align-items: center; justify-content: center;
    padding: 3rem;
    gap: 2rem;
    text-align: center;
    background: radial-gradient(ellipse at center, #142347 0%, #050a18 72%);
  }

  .ship-artifacts { display: flex; align-items: center; gap: 2.4rem; }

  .ship-folder {
    width: 220px;
    opacity: 0; transform: translateY(22px) scale(0.95);
    transition: opacity 0.8s ease, transform 0.8s ease;
  }
  .scene-ship.active .ship-folder { opacity: 1; transform: translateY(0) scale(1); transition-delay: 2s; }
  .ship-folder-tab {
    width: 90px; height: 16px;
    background: var(--gold); border-radius: 8px 8px 0 0;
    margin-left: 8px;
  }
  .ship-folder-body {
    background: linear-gradient(180deg, #f4c869, #d4a647);
    border-radius: 0 10px 10px 10px;
    padding: 1.1rem 1rem;
    box-shadow: 0 20px 50px rgba(0,0,0,0.45);
    text-align: left;
  }
  .ship-file {
    background: rgba(255,255,255,0.85);
    color: #1a2a4f;
    font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
    font-size: 0.85rem; font-weight: 600;
    padding: 0.5rem 0.7rem;
    border-radius: 6px;
    margin: 0.4rem 0;
    display: flex; align-items: center; gap: 0.5rem;
  }
  .ship-fi { color: var(--gold); }

  .ship-mp4 {
    width: 150px; height: 96px;
    border-radius: 12px;
    background: rgba(20, 35, 71, 0.7);
    border: 1px solid var(--gold);
    display: flex; flex-direction: column; align-items: center; justify-content: center;
    gap: 0.5rem;
    box-shadow: 0 16px 44px rgba(0,0,0,0.4);
    opacity: 0; transform: scale(0.8);
    transition: opacity 0.7s ease, transform 0.7s ease;
  }
  .scene-ship.active .ship-mp4 { opacity: 1; transform: scale(1); transition-delay: 7s; }
  .ship-mp4-play {
    width: 40px; height: 40px; border-radius: 50%;
    background: linear-gradient(135deg, var(--gold-bright), var(--gold));
    color: var(--navy-900);
    display: flex; align-items: center; justify-content: center;
    font-size: 1.1rem; padding-left: 3px;
  }
  .ship-mp4-label { font-size: 0.85rem; font-weight: 700; color: var(--text); letter-spacing: 0.1em; }

  .ship-hosts { display: flex; flex-wrap: wrap; justify-content: center; gap: 0.7rem; }
  .ship-hosts span {
    font-size: 0.85rem; font-weight: 600;
    color: var(--text-dim);
    border: 1px solid var(--border);
    border-radius: 999px;
    padding: 0.35rem 1rem;
    opacity: 0; transform: translateY(10px);
    transition: opacity 0.5s ease, transform 0.5s ease;
  }
  .scene-ship.active .ship-hosts span { opacity: 1; transform: translateY(0); }
  .scene-ship.active .ship-hosts span:nth-child(1) { transition-delay: 12.0s; }
  .scene-ship.active .ship-hosts span:nth-child(2) { transition-delay: 12.4s; }
  .scene-ship.active .ship-hosts span:nth-child(3) { transition-delay: 12.8s; }
  .scene-ship.active .ship-hosts span:nth-child(4) { transition-delay: 13.2s; }
  .scene-ship.active .ship-hosts span:nth-child(5) {
    transition-delay: 13.6s;
    color: var(--gold-bright); border-color: var(--gold);
  }

  .ship-cta {
    font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
    font-size: clamp(1.6rem, 3.4vw, 2.6rem);
    font-weight: 800;
    color: var(--navy-900);
    background: linear-gradient(135deg, var(--gold-bright), var(--gold));
    padding: 0.7rem 2rem;
    border-radius: 999px;
    box-shadow: 0 20px 50px rgba(212, 166, 71, 0.4);
    opacity: 0; transform: translateY(20px);
    transition: opacity 0.8s ease, transform 0.8s ease;
  }
  .scene-ship.active .ship-cta { opacity: 1; transform: translateY(0); transition-delay: 17.5s; animation: pulse 3s ease-out infinite 19s; }

  .ship-closer {
    font-size: clamp(1.1rem, 2.2vw, 1.5rem);
    font-style: italic;
    color: var(--gold-bright);
    opacity: 0; transform: translateY(14px);
    transition: opacity 1.1s ease, transform 1.1s ease;
  }
  .scene-ship.active .ship-closer { opacity: 1; transform: translateY(0); transition-delay: 22.5s; }
""",
    },
}

CHAPTERS = [
    {"number": 1, "title": "The Email Nobody Reads", "icon": "1", "segments": [
        {"id": "s1_email", "scene": "email",
         "narration": (
             "You need to explain something — a new product, a launch, "
             "an idea worth understanding. So you ask Claude to draft an email. "
             "And you get a wall of text. Clear, sure. But it lands in an inbox, "
             "gets half-skimmed, and the part you cared about most never lands. "
             "There's a better way to explain something — one that's visual, "
             "narrated, and actually easy to follow."
         ),
         "timedClasses": [
             {"at": 12, "addClass": "skimmed"},
             {"at": 16.5, "addClass": "better"},
         ]},
    ]},
    {"number": 2, "title": "Make a Narrated Webinar", "icon": "2", "segments": [
        {"id": "s2_webinar", "scene": "webinar",
         "narration": (
             "Instead of drafting an email, build a narrated webinar. "
             "It starts as one config file — webinar dot py — that holds "
             "your chapters, your narration, and your scenes, all in one place. "
             "From there, the skill sends your script to ElevenLabs for a real "
             "voiceover, animates a bespoke scene behind every line, and wires it "
             "into a player — a chapter sidebar, a progress bar, and slides that "
             "advance themselves in time with the voice. "
             "Visual. Narrated. Easy to understand. "
             "The same content you'd have buried in an email — "
             "now something people actually watch."
         )},
    ]},
    {"number": 3, "title": "Post It Anywhere", "icon": "3", "segments": [
        {"id": "s3_ship", "scene": "ship",
         "narration": (
             "And what you get is just a folder — an index dot html and an "
             "audio directory — plus an MP4 you can post straight to X. "
             "Drop it on any static host, or send the video. "
             "No server, no slide deck, no wall of text. "
             "It's a Claude Code skill: type slash narrated-webinar, "
             "hand it your material, and it builds the thing you just watched. "
             "This was the pitch. It was also the demo."
         )},
    ]},
]
